@"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-jv
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: $AKS_RG
  storageAccount: $STORAGE_ACCOUNT_NAME
  shareName: $SHARE_NAME  
  storeAccountKey: "false"  # false means driver would leverage kubelet identity to get account key https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#static-provisionbring-your-own-file-share
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
"@ > sc-azurefile-csi.yaml