@"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs-jv
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: $AKS_RG
  storageAccount: $STORAGE_ACCOUNT_NAME
  shareName: $SHARE_NAME_NFS  
  storeAccountKey: "false"  # false means driver would leverage kubelet identity to get account key https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#static-provisionbring-your-own-file-share
  protocol: nfs
"@ > sc-azurefile-csi-nfs.yaml